# Конфигурация умного планировщика путешествий
name: Умный планировщик путешествий
version: 1.1

# Пункты назначения
destinations:
  москва:
    id: 524901
    currency: RUB
    timezone: Europe/Moscow
    language: русский
    transport_type: поезд
    daily_budget: 3000
  
  санкт-петербург:
    id: 498817
    currency: RUB
    timezone: Europe/Moscow
    language: русский
    transport_type: поезд
    daily_budget: 3500
  
  сочи:
    id: 491422
    currency: RUB
    timezone: Europe/Moscow
    language: русский
    transport_type: самолет
    daily_budget: 4000
  
  париж:
    id: 2988507
    currency: EUR
    timezone: Europe/Paris
    language: французский
    transport_type: самолет
    daily_budget: 6000
  
  токио:
    id: 1850147
    currency: JPY
    timezone: Asia/Tokyo
    language: японский
    transport_type: самолет
    daily_budget: 7000

# Рекомендации по вещам
packing_lists:
  лето:
    обязательно:
      - легкая одежда
      - шорты/юбки
      - футболки
      - купальник/плавки
      - головной убор
      - солнцезащитные очки
      - крем от солнца
    опционально:
      - ветровка
      - вечерний наряд
      - спортивная обувь
  
  зима:
    обязательно:
      - теплая куртка
      - свитер
      - термобелье
      - шапка
      - шарф
      - перчатки
      - теплая обувь
    опционально:
      - влагостойкая обувь
      - плед для путешествий
      - термос
  
  весна осень:
    обязательно:
      - куртка от ветра/дождя
      - джинсы/брюки
      - свитер/кофта
      - зонт
      - удобная обувь
    опционально:
      - шапка
      - перчатки
      - сменная обувь

# Примерные цены в рублях (диапазоны)
estimated_costs:
  транспорт:
    самолет: 5000-15000
    поезд: 2000-8000
    автобус: 1000-5000
    такси_аэропорт: 500-2000
  
  проживание:
    отель: 2000-5000
    хостел: 500-1500
    квартира: 1500-4000
    вилла: 8000-20000
  
  питание:
    день: 500-2000
    ресторан: 1000-3000
    фастфуд: 300-800
    супермаркет: 400-1200
  
  развлечения:
    музей: 200-1000
    экскурсия: 500-3000
    сувениры: 300-2000
    театр: 800-2500
  
  транспорт_местный:
    метро_день: 150-500
    такси_поездка: 200-800
    аренда_авто_день: 1500-4000

# Полезные советы
travel_tips:
  общие:
    - Сделайте копии документов
    - Сообщите родным о маршруте
    - Заранее узнайте экстренные номера
    - Скачайте карты оффлайн
    - Изучите местные обычаи
    - Купите местную сим-карту
    - Установите приложения для навигации
  
  документы:
    - Паспорт/ID
    - Страховка
    - Билеты (распечатать + в телефоне)
    - Бронь отеля
    - Водительские права (если нужно)
    - Международные права (для аренды авто)
    - Студенческий билет (для скидок)
  
  безопасность:
    - Деньги и документы храните в разных местах
    - Сфотографируйте важные документы
    - Не носите все деньги с собой
    - Изучите безопасные районы города
  
  здоровье:
    - Возьмите базовые лекарства
    - Узнайте адреса ближайших аптек
    - Пейте бутилированную воду
    - Используйте солнцезащитный крем

# Курсы валют для конвертации (примерные)
exchange_rates:
  EUR: 95.5
  USD: 85.2
  JPY: 0.55
  GBP: 108.3
  CNY: 11.8
