# Конфигурация умного планировщика путешествий
name: Умный планировщик путешествий
version: 1.0

# Пункты назначения (добавьте свои)
destinations:
  Москва:
    id: 524901
    currency: RUB
    timezone: Europe/Moscow
    language: русский
  
  санкт-петербург:
    id: 498817
    currency: RUB
    timezone: Europe/Moscow
    language: русский

  сочи:
    id: 491422
    currency: RUB
    timezone: Europe/Moscow
    language: русский

  париж:
    id: 2988507
    currency: EUR
    timezone: Europe/Paris
    language: французский

  токио:
    id: 1850147
    currency: JPY
    timezone: Asia/Tokyo
    language: японский

# Рекомендации по вещам
packing_lists:
  лето:
    обязательно:
      - легкая одежда
      - шорты/юбки
      - футболки
      - купальник/плавки
      - головной убор
      - солнцезащитные очки
      - крем от солнца
  
  зима:
    обязательно:
      - теплая куртка
      - свитер
      - термобелье
      - шапка
      - шарф
      - перчатки
      - теплая обувь
  
  весна осень:
    обязательно:
      - куртка от ветра/дождя
      - джинсы/брюки
      - свитер/кофта
      - зонт
      - удобная обувь

# Примерные цены (можно изменить)
estimated_costs:
  транспорт:
    самолет: 5000-15000
    поезд: 2000-8000
    автобус: 1000-5000
  
  проживание:
    отель: 2000-5000
    хостел: 500-1500
    квартира: 1500-4000
  
  питание:
    день: 500-2000
    ресторан: 1000-3000
    фастфуд: 300-800
  
  развлечения:
    музей: 200-1000
    экскурсия: 500-3000
    сувениры: 300-2000

# Полезные советы
travel_tips:
  общие:
    - Сделайте копии документов
    - Сообщите родным о маршруте
    - Заранее узнайте экстренные номера
    - Скачайте карты оффлайн
    - Изучите местные обычаи
  
  документы:
    - Паспорт/ID
    - Страховка
    - Билеты (распечатать + в телефоне)
    - Бронь отеля
    - Водительские права (если нужно)
